name: ArmorWardrobe
version: 8.0
main: me.xgal.ward.Main
author: xGal
description: Armor Wardrobe.
commands:
    ward:
        description: Wardrobe.
    wget:
        description: Get the wardrobe item.